"""add_team_bans_table

Revision ID: 35d07bf9aaeb
Revises: f0a6ca7bbdf5
Create Date: 2026-02-24 15:13:38.697573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d07bf9aaeb'
down_revision: Union[str, Sequence[str], None] = 'f0a6ca7bbdf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_bans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False, comment='Match identifier'),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='Team ID (100 or 200)'),
    sa.Column('champion_id', sa.Integer(), nullable=False, comment='Banned champion ID'),
    sa.Column('pick_turn', sa.Integer(), nullable=False, comment='Ban order (1-5 per team)'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_bans_champion_id', 'team_bans', ['champion_id'], unique=False)
    op.create_index('ix_team_bans_match_id', 'team_bans', ['match_id'], unique=False)
    op.create_index('ix_team_bans_match_team', 'team_bans', ['match_id', 'team_id'], unique=False)
    op.alter_column('players', 'riot_id',
               existing_type=sa.VARCHAR(length=64),
               comment='Riot ID game name',
               existing_nullable=False)
    op.alter_column('players', 'tag_line',
               existing_type=sa.VARCHAR(length=16),
               comment='Riot ID tag line',
               existing_nullable=False)
    op.alter_column('players', 'puuid',
               existing_type=sa.VARCHAR(length=128),
               comment='Universal player ID',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'puuid',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='Universal player ID',
               existing_nullable=False)
    op.alter_column('players', 'tag_line',
               existing_type=sa.VARCHAR(length=16),
               comment=None,
               existing_comment='Riot ID tag line',
               existing_nullable=False)
    op.alter_column('players', 'riot_id',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Riot ID game name',
               existing_nullable=False)
    op.drop_index('ix_team_bans_match_team', table_name='team_bans')
    op.drop_index('ix_team_bans_match_id', table_name='team_bans')
    op.drop_index('ix_team_bans_champion_id', table_name='team_bans')
    op.drop_table('team_bans')
    # ### end Alembic commands ###
