"""create phase 1 raw tables

Revision ID: 499c867b9244
Revises: 
Create Date: 2026-02-23 10:59:29.750446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '499c867b9244'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('game_creation', sa.BigInteger(), nullable=False),
    sa.Column('game_duration', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('patch_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_game_creation'), 'matches', ['game_creation'], unique=False)
    op.create_index(op.f('ix_matches_queue_id'), 'matches', ['queue_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riot_id', sa.String(length=64), nullable=False),
    sa.Column('tag_line', sa.String(length=16), nullable=False),
    sa.Column('puuid', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_puuid'), 'players', ['puuid'], unique=True)
    op.create_table('participant_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('champion', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('gold_earned', sa.Integer(), nullable=False),
    sa.Column('total_damage', sa.Integer(), nullable=False),
    sa.Column('cs', sa.Integer(), nullable=False),
    sa.Column('vision_score', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participant_stats_champion'), 'participant_stats', ['champion'], unique=False)
    op.create_index(op.f('ix_participant_stats_match_id'), 'participant_stats', ['match_id'], unique=False)
    op.create_index(op.f('ix_participant_stats_player_id'), 'participant_stats', ['player_id'], unique=False)
    op.create_table('team_objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('towers', sa.Integer(), nullable=False),
    sa.Column('dragons', sa.Integer(), nullable=False),
    sa.Column('barons', sa.Integer(), nullable=False),
    sa.Column('win_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_objectives_match_id'), 'team_objectives', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_objectives_match_id'), table_name='team_objectives')
    op.drop_table('team_objectives')
    op.drop_index(op.f('ix_participant_stats_player_id'), table_name='participant_stats')
    op.drop_index(op.f('ix_participant_stats_match_id'), table_name='participant_stats')
    op.drop_index(op.f('ix_participant_stats_champion'), table_name='participant_stats')
    op.drop_table('participant_stats')
    op.drop_index(op.f('ix_players_puuid'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_queue_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_game_creation'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
