"""add draft_actions table

Revision ID: cbda3e7830e3
Revises: 35d07bf9aaeb
Create Date: 2026-03-05 12:19:18.636609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbda3e7830e3'
down_revision: Union[str, Sequence[str], None] = '35d07bf9aaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False, comment='Match identifier'),
    sa.Column('team_id', sa.Integer(), nullable=False, comment='Team ID (100 or 200)'),
    sa.Column('action_type', sa.Enum('PICK', 'BAN', name='action_type_enum'), nullable=False, comment='Action type (PICK or BAN)'),
    sa.Column('phase', sa.Enum('PICK', 'BAN', name='draft_phase_enum'), nullable=False, comment='Draft phase (PICK or BAN). Typically mirrors action_type.'),
    sa.Column('champion_id', sa.Integer(), nullable=False, comment='Champion ID involved in the action'),
    sa.Column('role', sa.String(length=32), nullable=True, comment='Role/position for picks (TOP, JUNGLE, MIDDLE, BOTTOM, UTILITY); NULL for bans'),
    sa.Column('turn', sa.Integer(), nullable=False, comment='Order inside the phase per team. BAN: 1-5 per team. PICK: deterministic 1-5 per team (MVP).'),
    sa.Column('action_order', sa.Integer(), nullable=True, comment='Optional global draft order if available; otherwise NULL'),
    sa.CheckConstraint('team_id IN (100, 200)', name='ck_draft_actions_team_id'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'phase', 'team_id', 'turn', name='uq_draft_actions_match_phase_team_turn')
    )
    op.create_index('ix_draft_actions_action_type', 'draft_actions', ['action_type'], unique=False)
    op.create_index('ix_draft_actions_champion_id', 'draft_actions', ['champion_id'], unique=False)
    op.create_index('ix_draft_actions_match_id', 'draft_actions', ['match_id'], unique=False)
    op.create_index('ix_draft_actions_match_order', 'draft_actions', ['match_id', 'action_order'], unique=False)
    op.create_index('ix_draft_actions_match_phase', 'draft_actions', ['match_id', 'phase'], unique=False)
    op.create_index('ix_draft_actions_match_phase_turn', 'draft_actions', ['match_id', 'phase', 'turn'], unique=False)
    op.create_index('ix_draft_actions_match_team', 'draft_actions', ['match_id', 'team_id'], unique=False)
    op.create_index('ix_draft_actions_match_team_phase', 'draft_actions', ['match_id', 'team_id', 'phase'], unique=False)
    op.create_index('ix_draft_actions_role', 'draft_actions', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_draft_actions_role', table_name='draft_actions')
    op.drop_index('ix_draft_actions_match_team_phase', table_name='draft_actions')
    op.drop_index('ix_draft_actions_match_team', table_name='draft_actions')
    op.drop_index('ix_draft_actions_match_phase_turn', table_name='draft_actions')
    op.drop_index('ix_draft_actions_match_phase', table_name='draft_actions')
    op.drop_index('ix_draft_actions_match_order', table_name='draft_actions')
    op.drop_index('ix_draft_actions_match_id', table_name='draft_actions')
    op.drop_index('ix_draft_actions_champion_id', table_name='draft_actions')
    op.drop_index('ix_draft_actions_action_type', table_name='draft_actions')
    op.drop_table('draft_actions')
    # ### end Alembic commands ###
