"""create derived_metrics table

Revision ID: e22f3c14ba64
Revises: 499c867b9244
Create Date: 2026-02-24 09:24:18.192604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22f3c14ba64'
down_revision: Union[str, Sequence[str], None] = '499c867b9244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derived_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('kda', sa.Float(), nullable=True),
    sa.Column('cs_per_min', sa.Float(), nullable=True),
    sa.Column('gold_per_min', sa.Float(), nullable=True),
    sa.Column('kill_participation', sa.Float(), nullable=True),
    sa.Column('damage_share', sa.Float(), nullable=True),
    sa.Column('vision_per_min', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'puuid', name='uq_derived_metrics_match_puuid')
    )
    op.create_index('ix_derived_metrics_match_id', 'derived_metrics', ['match_id'], unique=False)
    op.create_index('ix_derived_metrics_puuid', 'derived_metrics', ['puuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_derived_metrics_puuid', table_name='derived_metrics')
    op.drop_index('ix_derived_metrics_match_id', table_name='derived_metrics')
    op.drop_table('derived_metrics')
    # ### end Alembic commands ###
